name = "PNOD"
uuid = "dd7b5c11-b078-4944-ab42-7d7934415448"
authors = ["Ling Liang", "Haizhao Yang"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
